# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
os: osx
osx_image: xcode8

-before_install:
 - |
    gem install xcpretty slather -N
 
script:
- |
    set -o pipefail
    xcodebuild clean test -workspace Example/Trigger.xcworkspace -scheme Trigger-Example -destination "platform=iOS Simulator,name=iPhone 6 Plus,OS=latest" ONLY_ACTIVE_ARCH=NO | xcpretty -c
